name: grype psqldocker

on:
  push:
    branches: [ main ]
    paths: [ psqldocker/** ]

jobs:
  scan-source:
    name: Scan source code
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: anchore/scan-action@v3
        id: scan
        with:
          path: psqldocker
          fail-build: true
          acs-report-enable: true
          severity-cutoff: medium

      - name: upload Anchore scan SARIF report
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}