on:
  # Trigger the workflow on push request if the files
  # in ./psqltest package were modified
  push:
    paths:
      - psqltest/**

env:
  PACKAGE: psqltest

name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./${{ env.PACKAGE }}/
          args: -c=$GITHUB_WORKSPACE/.golangci.yml

      - name: Run tests
        run: make test -C $GITHUB_WORKSPACE/${{ env.PACKAGE }}