on:
  # Trigger the workflow on push request if the files
  # in ./pubsub package were modified
  push:
    branches:
      - main
    paths:
      - grpc/**

env:
  PACKAGE: grpc

name: test-grpc
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
          working-directory: ./${{ env.PACKAGE }}/
          args: -c=$GITHUB_WORKSPACE/.golangci.yml

      - name: Run tests
        run: make test -C $GITHUB_WORKSPACE/${{ env.PACKAGE }}